Update kubernetes engine cluster version.
According to https://cloud.google.com/kubernetes-engine/release-notes#june-28-2018, 1.10.4-gke.0 is no longer available but 1.10.5-gke.0 now is.

With the old version I get:

```
$ gcloud container clusters create quickstart --cluster-version=1.10.4-gke.0 --zone us-east1-b --project jblatt-test
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=master version "1.10.4-gke.0" is unsupported.
```