suggest a more recent gke minor version (#2283)
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.10.5-gke.0" is unsupported.

(cherry picked from commit 4a49a2d1e75f4b1d2a2c9aa7490a595dc85e97c4)