Cherry-pick latest changes from master. (#2308)
* Fix extra brace (#2263)

(cherry picked from commit 586c740d36317ace0c5ed84ce1addb75e330b724)

* Translate help/ops/component-debugging into Chinese (#2255)

Rebase component-logging

(cherry picked from commit 8d80491780f10f848337ae9a141080c873c642e4)

* Translate help/faq/traffic-management into Chinese;Fix format (#2267)

(cherry picked from commit 034548e67a6540e518260c6e7d41b5bd1682bed6)

* Translate help/faq/telemery into Chinese (#2269)

* Translate help/faq/telemery into Chinese;Fix space

* Fix ci failed

(cherry picked from commit ada8c96a66462c63bfe22d61e411c4f97f97e48c)

* translate /help/ops/missing-metrics (#2265)

* translate /help/ops/missing-metrics

* change title

(cherry picked from commit 60296ae6fce13f20175eb217d7ba331802bb9832)

* Extend the secure ingress task with multiple ingress certificates/hosts (#2238)

* generate certificates in httpbin.example.com directory

* add initial section for ingress for multiple hosts

* add a cleanup step for the directories related to certificates

* fix formatting

* add subsection: Redeploy istio-ingressgateway with the new certificates

* rename httpbin-gateway into mygateway

* add redeployment of Gateway for two hosts

* add -o /dev/null -s -w "%{http_code}\n" to the bookinfo's curl

* fix italics in sending a request to bookinfo

* add verify that httpbin.example.com is accessible as previously

* add -v to curl to bookinfo, show certificates printed

* remove -n istio-system from virtualservice bookinfo

* add Host header to curl requests

* put empty lines around the code blocks

* fix spell checker errors

(cherry picked from commit d5cb6942851db8ed4272b8acf658e3d895fb4d11)

* add 'location: MESH_EXTERNAL' to the service entries (#2226)

it is currently not required, however for the sake of proper configuration
it should be added

(cherry picked from commit b2bb9c5f2da80d465c39479b1912a2f41b0b9d01)

* add DestinationRule to example (#2261)

(cherry picked from commit beeb9c341dd5e72c8a6e212df344e0ba60fb898f)

* fix sample RbacConfig in concept page. (#2253)

(cherry picked from commit 053efb78f9e52fb93600cccb7f1d48540d12634b)

* Highlight "Istio multicluster" in example document. (#2196)

(cherry picked from commit 670fb9eba0161362e5a67fdf54288e86eeca5a50)

* fix mistranslate of /zh/docs/setup/kubernetes/helm-install (#2270)

* fix mistranslate of /zh/docs/setup/kubernetes/helm-install

* fix related link of changed title

(cherry picked from commit 54327f7286ecd79e34d60008fbdb033dcb693a0b)

* translation：/content/help/faq/mixer/index.md (#2250)

* traslation:/content/docs/concepts/index.md

* traslation:/content/docs/reference/config/authorization/_index.md

* traslation:/content/docs/reference/config/authorization/_index.md

* traslation:/content/docs/reference/config/authorization/_index.md

* trigger

* trigger

* translation:/content/help/faq/mixer/index.md

* translation:/content/help/faq/mixer/index.md 格式问题

(cherry picked from commit e497125203dbad4f0614b1a63871c8fde0b1d2f4)

* Translate expression-language into chinese (#2134)

* Translate expression-language into chinese

* add spaces between chinese and english words, for expression-language page (#2134)

* delete repeat character,add spaces (#2134)

* add period to title end (#2134)

* remove alias

* remove spelling

(cherry picked from commit 9dd2adb8dbce8ac2a381ac94f5cf6a0636cb3b64)

* Translate into Chinese: help/faq/security/https-overlay.md (#2272)

* Translate into Chinese: help/faq/security/https-overlay.md

* Update https-overlay.md

* Update https-overlay.md

* Update https-overlay.md

* Update https-overlay.md

* Trigger CI

* Trigger CI

* Update https-overlay.md

(cherry picked from commit 32529b099a61c070e167efc6dcafba58ba566cbb)

* Translate into Chinese: help/faq/security/check-policy.md (#2276)

* Translate into Chinese: help/faq/security/check-policy.md

* Update check-policy.md

* Update CI

(cherry picked from commit 5064a5fc5028541f15778b70dd60b9339e039628)

* adding schedule to istio twich live stream page (#2274)

* Adding twitch stream schedule to content

* --amend

(cherry picked from commit 86c0dd3eac807f886410bac73d844e73e9b4a888)

* Spell Lisa's name correctly (#2279)

(cherry picked from commit b73b6a8ac7852e1e9a8ba4c6572b62d65c8585a7)

* Switch to Hugo 0.47 (#2288)

- Fixes the bug where not all of our files would get the right lastmod
time extracted from GitHub.

- Fixes most of the cases of bad HTML output around the use of {{<text>}}. There's
still a single bad case which I'll report to the Hugo folks.

- Use Hugo's new --minify option to minify HTML instead of having to use the
separate and slow html-minifier program.

- Fix some bad HTML on the landing page.

(cherry picked from commit be7c374f297a712fb6e5cd1be98b656a3b52732f)

* suggest a more recent gke minor version (#2283)

ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Master version "1.10.5-gke.0" is unsupported.

(cherry picked from commit 4a49a2d1e75f4b1d2a2c9aa7490a595dc85e97c4)

* translate update setup requirement (#2282)

(cherry picked from commit 083de5b4c6575af72e36b5c09f36f91e713e73ea)

* translate: update taks/traffic-management/egress (#2280)

(cherry picked from commit c10b35529088390985558f521c15e7b9dd29657a)

* Delete special chars and turn on HTML checking (#2292)

* Delete special chars and turn on HTML checking

- Refer to #2289 and issue #2290
- Delete the special chars in Chinese content
- Turn on HTML checking to highlight problems

* delete the redundant period

(cherry picked from commit 91d2481bc5d993b4868b6257b3147fdae1082313)

* remove extra space before dot (#2305)

(cherry picked from commit f8f20afc1762559ad8ca71407d599aa8ee8e9965)

* Bunch of site fixes & improvements. (#2306)

- Correct the use of OpenGraph annotations. I used the wrong attribute name, so the
annotations were never recognized.

- Added support for Twitter cards to our site, improving the experience of referencing
the site from Twitter posts.

- Added support for the twitter: front matter field for use in blog posts. Specifying this
front-matter entry will show the author's twitter address on the blog post, and will
add a Twitter card entry to the page noting the author's address.

- Renamed the page_icon front matter field to just icon to be consistent with other
entries.

- Made it so the subtitle front matter field can be used anywhere, not just on blog posts.

- Added a lint check to ensure subtitles don't end with a period.

- We now insert an "author" metadata entry whenever the attribution: front matter
field is used.

(cherry picked from commit 5e29d61ff26692f87a3e179e266bfaefaf9ac15b)